name: docs

on:
  workflow_dispatch: # Allows manual triggering
    inputs:
      reason:
        description: "Reason for manual deployment"
        required: false
        default: "Manual documentation update"
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"

jobs:
  deploy-docs:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # This is required for pushing to gh-pages
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
